INPUT:
  MIN_SIZE_TRAIN: 512
  MAX_SIZE_TRAIN: 512

MODEL:
  NAME: "bninception"
  WEIGHT: "/unsullied/sharefs/ouxiaoxuan/isilon/dl_backbone/tools/bnincep_bce_pre/model_0025000.pth"

SOLVER:
  METHOD: "SGD"
  MAX_ITER: 40000
  BASE_LR: 0.03
  GAMMA: 0.5
  STEPS: (5000, 10000, 20000)
  IMS_PER_BATCH: 128

OUTPUT_DIR: "/unsullied/sharefs/ouxiaoxuan/isilon/dl_backbone/tools/bnincep_bce_pre"