INPUT:
  MIN_SIZE_TRAIN: 512
  MAX_SIZE_TRAIN: 512

MODEL:
  NAME: "gapnet-pl"
  WEIGHT: ""

DATALOADER:
  NUM_WORKERS: 8

SOLVER:
  FINETUNE: "off"
  TRAIN_EPOCH: 100
  BASE_LR: 0.05
  GAMMA: 0.5
  IMS_PER_BATCH: 256

TEST:
  IMS_PER_BATCH: 128

OUTPUT_DIR: "/unsullied/sharefs/ouxiaoxuan/isilon/dl_backbone/tools/dump/gapnet_bce"