INPUT:
  MIN_SIZE_TRAIN: 512
  MAX_SIZE_TRAIN: 512

SOLVER:
  BASE_LR: 0.03
  GAMMA: 0.5
  STEPS: (15000, 20000, 25000, 35000)
  IMS_PER_BATCH: 32

OUTPUT_DIR: "/unsullied/sharefs/ouxiaoxuan/isilon/dl_backbone/tools/incep_bce_sgd"