INPUT:
  MIN_SIZE_TRAIN: 512
  MAX_SIZE_TRAIN: 512

MODEL:
  NAME: "resnet34"
  WEIGHT: ""

SOLVER:
  FINETUNE: "on"
  TRAIN_EPOCH: 100
  BASE_LR: 0.03
  FINETUNE_EPOCH: 10
  FINETUNE_LR: 0.03
  GAMMA: 0.5
  IMS_PER_BATCH: 64

TEST:
  IMS_PER_BATCH: 64

OUTPUT_DIR: "/unsullied/sharefs/ouxiaoxuan/isilon/dl_backbone/tools/dump/res34_bce_pre"