INPUT:
  MIN_SIZE_TRAIN: 512
  MAX_SIZE_TRAIN: 512

MODEL:
  NAME: "resnet50"
  WEIGHT: "model_0037500.pth"

SOLVER:
  FINETUNE: "on"
  TRAIN_EPOCH: 100
  BASE_LR: 0.03
  FINETUNE_EPOCH: 5
  FINETUNE_LR: 0.03
  PATIENCE: 5000
  GAMMA: 0.5
  IMS_PER_BATCH: 32
  CHECKPOINT_PERIOD: 2500
TEST:
  IMS_PER_BATCH: 64

OUTPUT_DIR: "/unsullied/sharefs/ouxiaoxuan/isilon/dl_backbone/tools/dump/res50_bce_pre"