INPUT:
  MIN_SIZE_TRAIN: 512
  MAX_SIZE_TRAIN: 512

MODEL:
  NAME: "resnet50"
  WEIGHT: "/unsullied/sharefs/ouxiaoxuan/isilon/dl_backbone/tools/res50_bce_sgd/model_0049999.pth"

SOLVER:
  METHOD: "SGD"
  MAX_ITER: 50000
  BASE_LR: 0.02
  GAMMA: 0.5
  STEPS: (15000, 20000, 25000, 35000)
  IMS_PER_BATCH: 96

OUTPUT_DIR: "/unsullied/sharefs/ouxiaoxuan/isilon/dl_backbone/tools/res50_bce_sgd"